### ISSUE TITLE
Migrate pipelines to Github Actions

### ISSUE THREAD

**Issue by nadiamoe** [grafana/synthetic-monitoring-agent#841]
There are roughly three pipelines that need to be migrated:

```[tasklist]
### Tasks
- [ ] "Push/pr" pipeline, a.k.a. build, lint, test, etc. #842
- [ ] Release pipeline for container images (dockerhub, ghcr)
- [ ] Release pipeline for linux packages
- [ ] Technically also part of the release pipeline, but better done on a separate PR, triggering argo workflows
```
